# Copyright IBM Corp. 2025, 2026
# SPDX-License-Identifier: MPL-2.0

"""The exact public SDK surface the workflow layer depends on.

Core may be regenerated from an OpenAPI spec. When that happens, a renamed
method or a dropped parameter must fail loudly here rather than at runtime in a
user's pipeline, so every ``(resource, method)`` pair the workflows call is
declared below and checked against a committed snapshot by
``tests/contract/test_public_surface.py``.

Add a pair here whenever a workflow starts calling a new method, then run
``make surface-snapshot`` to re-record the signatures.
"""

from __future__ import annotations

__all__ = ["REQUIRED"]

#: Every ``(resource, method)`` reached from ``pytfe.workflows``.
REQUIRED: frozenset[tuple[str, str]] = frozenset(
    {
        ("admin.organizations", "list"),
        ("admin.runs", "list"),
        ("admin.saml_settings", "update"),
        ("admin.scim_settings", "update"),
        ("admin.smtp_settings", "update"),
        ("admin.terraform_versions", "list"),
        ("admin.users", "list"),
        ("agent_pools", "assign_to_workspaces"),
        ("agent_pools", "create"),
        ("agent_pools", "list"),
        ("agent_tokens", "create"),
        ("agent_tokens", "list"),
        ("agents", "list"),
        ("applies", "errored_state"),
        ("applies", "logs"),
        ("applies", "read"),
        ("comments", "create"),
        ("configuration_versions", "create"),
        ("configuration_versions", "read"),
        ("configuration_versions", "upload_tar_gzip"),
        ("cost_estimates", "read"),
        ("no_code_modules", "create_workspace"),
        ("notification_configurations", "create"),
        ("notification_configurations", "list"),
        ("notification_configurations", "update"),
        ("organization_tokens", "read"),
        ("organizations", "create"),
        ("organizations", "list"),
        ("plans", "logs"),
        ("plans", "read"),
        ("plans", "read_for_run"),
        ("plans", "read_json_output"),
        ("plans", "read_json_output_for_run"),
        ("policy_checks", "list"),
        ("policy_checks", "override"),
        ("policy_sets", "add_workspaces"),
        ("policy_sets", "create"),
        ("policy_sets", "list"),
        ("policy_sets", "update"),
        ("projects", "create"),
        ("projects", "list"),
        ("projects", "move_workspaces"),
        ("projects", "update"),
        ("registry_modules", "create"),
        ("registry_modules", "create_version"),
        ("registry_modules", "list_versions"),
        ("registry_modules", "read"),
        ("registry_modules", "read_version"),
        ("registry_modules", "upload_tar_gzip"),
        ("run_tasks", "create"),
        ("run_tasks", "list"),
        ("run_tasks", "update"),
        ("run_triggers", "create"),
        ("run_triggers", "delete"),
        ("run_triggers", "list"),
        ("runs", "apply"),
        ("runs", "cancel"),
        ("runs", "create"),
        ("runs", "discard"),
        ("runs", "force_cancel"),
        ("runs", "list"),
        ("runs", "read"),
        ("state_version_outputs", "read_current"),
        ("state_versions", "download"),
        ("state_versions", "list"),
        ("state_versions", "read"),
        ("state_versions", "read_current"),
        ("state_versions", "rollback"),
        ("state_versions", "upload"),
        ("team_tokens", "list"),
        ("team_workspace_accesses", "add"),
        ("team_workspace_accesses", "list"),
        ("team_workspace_accesses", "update"),
        ("teams", "add_users"),
        ("teams", "create"),
        ("teams", "list"),
        ("teams", "list_users"),
        ("teams", "remove_users"),
        ("variable_set_variables", "create"),
        ("variable_set_variables", "delete"),
        ("variable_set_variables", "list"),
        ("variable_set_variables", "update"),
        ("variable_sets", "apply_to_projects"),
        ("variable_sets", "apply_to_workspaces"),
        ("variable_sets", "create"),
        ("variable_sets", "list"),
        ("variable_sets", "update"),
        ("variables", "create"),
        ("variables", "delete"),
        ("variables", "list"),
        ("variables", "update"),
        ("workspace_resources", "list"),
        ("workspace_run_tasks", "create"),
        ("workspace_run_tasks", "list"),
        ("workspace_run_tasks", "update"),
        ("workspaces", "add_tags"),
        ("workspaces", "create"),
        ("workspaces", "delete_by_id"),
        ("workspaces", "force_unlock"),
        ("workspaces", "list"),
        ("workspaces", "lock"),
        ("workspaces", "read"),
        ("workspaces", "read_by_id"),
        ("workspaces", "remove_tags"),
        ("workspaces", "safe_delete_by_id"),
        ("workspaces", "unlock"),
        ("workspaces", "update_by_id"),
    }
)
